name: Generate TypeScript Documentation

on:
  push:
    branches:
      - main
      - docs
  pull_request:
    branches:
      - main

jobs:
  swagger-gh-pages:
    runs-on: ubuntu-latest   

    steps:
      - name: Instantiate package
        uses: actions/checkout@v2

      - name: Install typedoc
        run: yarn add typedoc

      - name: Generate typedoc
        run: yarn typedoc src/index.ts --out build        

      - name: Install git
        run: apt-get install git -y

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build